[package]
name = "a52-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = "0.3.4"
lazy_static = "1.4.0"
libc = "0.2.102"

[lib]
crate-type = ["staticlib"]
